Разметка всех страниц
htmlacademy-htmlcss/2257959-sedona-36 pull request #2
Opened 2023-01-22 17:35 UTC by Teihden

2023-01-22 19:22 UTC, Kartaviy-arteom requested changes

2023-01-22 19:22 UTC, Kartaviy-arteom commented on catalog.html
> +      </header>
лучше объединить тогда эту часть со следующей секцией

2023-01-22 19:22 UTC, Kartaviy-arteom commented on catalog.html
> +        <form class="catalog-filter" action="https://echo.htmlacademy.ru/" method="get" oninput="outputmin.value=rangemin.value, outputmax.value=rangemax.value">
тебе не нужно писать js инлайном, это очень устаревшая практика

2023-01-22 19:22 UTC, Kartaviy-arteom commented on catalog.html
> +              </li>
эти чекбоксы нужно тоже сгруппировать, это все инфраструктура

2023-01-22 19:22 UTC, Kartaviy-arteom commented on catalog.html
> +        <ul class="pagination">
ol подойдет чуть лучше

2023-01-22 19:22 UTC, Kartaviy-arteom commented on index.html
> +      </div>
из вот этого можно собрать первую секцию

2023-01-22 19:22 UTC, Kartaviy-arteom commented on index.html
> +          </header>
тебе здесь не нужен и далее хедер. Можно заголовок с параграфом вообще дополнительно не оборачивать, если нужно будет для стилей только, можно просто дивом

2023-01-22 19:22 UTC, Kartaviy-arteom commented on index.html
> +          </header>
тут heder не нужен, он сюда не подходит, да и не нужен

2023-01-22 20:01 UTC, Teihden commented on catalog.html
> +              </li>
Артём, тут не понял: чекбоксы же уже входят в список, который в свою очередь вложен в fieldset.

https://github.com/htmlacademy-htmlcss/2257959-sedona-36/blob/c9214fb5ae735af5bd04d2c875c53af8e2fd6fb7/catalog.html#L59-L75

2023-01-25 11:56 UTC, Kartaviy-arteom approved these changes

2023-01-25 11:56 UTC, Kartaviy-arteom commented on catalog.html
> +        <header class="catalog-main-header">
этот хедер особо не к чему здесь, если ты его уберешь ничего не изменится

2023-01-25 11:56 UTC, Kartaviy-arteom commented on catalog.html
> +          </fieldset>
на этот элемент пока можно не тратить время, он будет показан в курсе лекций с реализацией без input type="range"

2023-01-25 11:56 UTC, Kartaviy-arteom commented on catalog.html
> +        <h2 class="visually-hidden">Найденные предложения жилья</h2>
Я бы сказал это подбор жилья, в заголовке

2023-01-25 11:57 UTC, merged